FROM amazoncorretto:17

RUN yum -y install tzdata && yum clean all
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# GitHub Actions에서 실제 jar 경로를 build-arg로 넘김
ARG JAR_FILE
COPY ${JAR_FILE} /app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-Duser.timezone=Asia/Seoul", "-jar", "/app.jar"]