spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

ncp:
  object-storage:
    endpoint: ${OBJECT_STORAGE_ENDPOINT}
    region: kr-standard
    bucket: ${OBJECT_STORAGE_BUCKET_NAME}
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    default-prefix: uploads-local